### ISSUE TITLE
bugs report 

### ISSUE THREAD

**Issue by AlkenePan** [FortuneC00kie/bug-monitor#1]
### requirements.txt
```
python-dateutil
pyyaml
```

### database
```
diff --git a/lib/mongodb.py b/lib/mongodb.py
index 68bc5f8..11b84c2 100644
--- a/lib/mongodb.py
+++ b/lib/mongodb.py
@@ -69,6 +69,8 @@ def bug_early_clean():
     """
     自动清理一个月之前保存的漏洞信息
     """
+    db = conn_mongo()
+    database = db.bugdata
     before_data = datetime.date.today() - relativedelta(months=+1)
     early = before_data.strftime("%Y-%m-%d")
     database.remove({"addtime":{"$lt":early}})
```

### seebug eval
I install PyV8 with this: https://github.com/brokenseal/PyV8-OS-X
```
Traceback (most recent call last):
  File "index.py", line 40, in <module>
    seebug_monitor()
  File "index.py", line 24, in seebug_monitor
    seebug_crawer()
  File "/Users/xx/project/bug-monitor/seebug/seebug_crawer.py", line 25, in seebug_crawer
    cookie = cookie_init()
  File "/Users/xx/project/bug-monitor/seebug/seebug_cookie_init.py", line 62, in cookie_init
    return get_jsluid(req)
  File "/Users/xx/project/bug-monitor/seebug/seebug_cookie_init.py", line 24, in get_jsluid
    get_jsl_clearance(req, post_cookie)
  File "/Users/xx/project/bug-monitor/seebug/seebug_cookie_init.py", line 47, in get_jsl_clearance
    ctxt.eval(script)
Boost.Python.ArgumentError: Python argument types in
    JSContext.eval(JSContext, unicode)
did not match C++ signature:
    eval(CContext {lvalue}, std::string source, std::string name='', int line=-1, int col=-1, boost::python::api::object precompiled=None)
```

### cve module  import error

import in __init_.py first

```
diff --git a/cve/__init__.py b/cve/__init__.py
index 8cc1d1b..dede444 100644
--- a/cve/__init__.py
+++ b/cve/__init__.py
@@ -1,3 +1,4 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 -*-
-# @Author  : mr.chery (mr.chery666@gmail.com)
\ No newline at end of file
+# @Author  : mr.chery (mr.chery666@gmail.com)
+from cve import *
```

### config path error
```
Traceback (most recent call last):
  File "index.py", line 6, in <module>
    from cve import *
  File "/Users/xxx/project/bug-monitor/cve/__init__.py", line 4, in <module>
    from cve import *
  File "/Users/xxx/project/bug-monitor/cve/cve.py", line 13, in <module>
    with open('../config.yaml', 'r') as f:
IOError: [Errno 2] No such file or directory: '../config.yaml'
```

I got interest in this project, but too many bugs, I will pull request later.

**Comment by AlkenePan** [comment]
WTF?
![image](https://user-images.githubusercontent.com/8273781/35549951-f82b7456-05c2-11e8-92e8-55d07db89ac8.png)
![image](https://user-images.githubusercontent.com/8273781/35549966-076fc03e-05c3-11e8-960a-0509a2f811f2.png)
and crawer ? clawer ?

**Comment by Shadow2chery** [comment]
thanks for focus my project.these bug has been repaired,hope you can countine to find more bug to tell me ,this will make this project more strong💪🏻
